### ISSUE TITLE
where is get_bldg_elements function?

### ISSUE THREAD

**Issue by manapshymyr-OB** [ai4up/eubucco#3]
`Traceback (most recent call last):
  File "/manap_dir/planetary/eubucco/eubucco/preproc/parsing.py", line 1167, in <module>
    parse(test_run=False, arg_as_param=None)
  File "/manap_dir/planetary/eubucco/eubucco/preproc/parsing.py", line 935, in parse
    gdf, count_multipoly, dict_val = parse_gml(file_path, p['dataset_name'], p['bldg_elem'],
  File "/manap_dir/planetary/eubucco/eubucco/preproc/parsing.py", line 638, in parse_gml
    bldg_elem_list = get_bldg_elements(gml, gml_root, bldg_elem)
NameError: name 'get_bldg_elements' is not defined`

**Comment by wagnerfe** [comment]
Dear @manapshymyr-OB, Thank you very much for your comment! 
The function 'get_bldg_elements' is located in the submodule ufo_map.Preprocessing.parsing.py. The code from ufo map is included as a submodule in eubucco. When cloning the repo, have you checked that you also include the ufo-map submodule?

**Comment by FlorianNachtigall** [comment]
Closing due to inactivity. Please feel free to reopen, if your problem persists.
